hms_prj/hms_prj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('',include('hotel.urls'))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hms_prj/hotel/urls.py

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib import admin
from django.urls import path
from .views import RoomList,BookingList,RoomDetailView,CancelBookingView,booked
app_name='hotel'
urlpatterns=[
    path('',RoomList,name="RoomList"),
    path('booking_list/',BookingList.as_view(),name="BookingList"),
    path('booking/cancel/<pk>',CancelBookingView.as_view(),name="CancelBookingView"),
    path('room/<str:category>',RoomDetailView.as_view(),name="RoomDetailView"),
    path('booked/',booked,name="booked")
]

hms_prj/hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
# Create your models here.
class Room(models.Model):
    ROOM_CATEGORIES=(
        ('YAC','AC'),
        ('NAC','NON'),
        ('DEL','DELUXE'),
        ('KIN','KING'),
        ('QUE','QUEEN'),

    )
    number=models.IntegerField()
    category=models.CharField(max_length=3,choices=ROOM_CATEGORIES)
    beds=models.IntegerField()
    capacity=models.IntegerField()
    def __str__(self):
        return f'{self.number}.{self.category} with {self.beds} beds for {self.capacity} people'
class Bookings(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    check_in=models.DateTimeField()
    check_out=models.DateTimeField()        
    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'
    def get_room_category(self):
        room_categories=dict(self.room.ROOM_CATEGORIES)
        room_category=room_categories.get(self.room.category)
        return room_category
    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])
    

hms_prj/hotel/forms.py
from django import forms
class AvaibilityForm(forms.Form):
    check_in=forms.DateTimeField(required=True,input_formats=["%Y-%m-%dT%H:%M",])
    check_out=forms.DateTimeField(required=True,input_formats=["%Y-%m-%dT%H:%M",])
  

hms_prj/hotel/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.views.generic import ListView,FormView,View,DeleteView
from django.urls import reverse,reverse_lazy
from .models import Room,Bookings
from .forms import AvaibilityForm
from django.contrib import messages
from hotel.bookings.avaibility import check_avaibility 
def RoomList(request):
    room=Room.objects.all()[0]
    room_categories=dict(room.ROOM_CATEGORIES)
    
    room_values=room_categories.values()
    room_list=[]
    for room_category in room_categories:
        room=room_categories.get(room_category)
        room_url=reverse('hotel:RoomDetailView',kwargs={'category':room_category})
        room_list.append((room,room_url))
    context={
        "room_list":room_list
    }
    return render(request,'room_list.html',context)
class BookingList(ListView):
    model=Bookings
    def get_queryset(self,*args,**kwargs) :
        if self.request.user.is_staff:
            booking_list=Bookings.objects.all()
            return booking_list
        else:
            booking_list=Bookings.objects.filter(user=self.request.user)
            return booking_list   
class RoomDetailView(View):
    def get(self,request,*args,**kwargs):
        category=self.kwargs.get('category',None)
        room_list=Room.objects.filter(category=category)
        form=AvaibilityForm()
        if len(room_list)>0:
            room=room_list[0]
            room_category=dict(room.ROOM_CATEGORIES).get(room.category,None)
            context={
            'room_category': room_category,
            'form':form,
             }
            return render(request,'room_detail_view.html',context)
        else:
            return HttpResponse("Category Not Exist") 
    def post(self,request,*args,**kwargs):
        category=self.kwargs.get('category',None)
        room_list=Room.objects.filter(category=category)
        available_rooms=[]
        form=AvaibilityForm(self.request.POST)
        if form.is_valid():
            data=form.cleaned_data
        for room in room_list:
            if check_avaibility(room,data['check_in'],data['check_out']):
                available_rooms.append(room)
        if(len(available_rooms)>0):
            room=available_rooms[0]
            booking=Bookings.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
                )
            booking.save()
            return HttpResponse("booked")
        else:
            return HttpResponse("This Category Of rooms are booked")

class BookingView(FormView):
    form_class=AvaibilityForm
    template_name='avaibility_form.html'
    def form_valid(self, form):
        data=form.cleaned_data
        room_list=Room.objects.filter(category=data['room_category'])
        available_rooms=[]
        for room in room_list:
            if check_avaibility(room,data['check_in'],data['check_out']):
                available_rooms.append(room)
        if(len(available_rooms)>0):
            room=available_rooms[0]
            booking=Bookings.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
                )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse("This Category Of rooms are booked")
class CancelBookingView(DeleteView):
    model = Bookings
    template_name='booking_cancel_view.html'
    success_url=reverse_lazy('hotel:BookingList')
def booked(request):
    messages.success(request, 'Your message was successfully sent!')
    return render(request,'room_list.html')

hms_prj/hotel/templates/avaibility_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit">Book Room</button>
</form>
</body>
</html>

hms_prj/hotel/templates/booked.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

hms_prj/hotel/templates/booking_cancel_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Room Details</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css'%}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->


</head>
<body>
	<div id="booking" class="section">
		<div class="section-center">
					
	<div class="container">
		<a class="btn btn-primary" href="{% url 'hotel:RoomList' %}"> Home</a>
	</div>
                     
			<div class="container">
				<div class="row">
					<div class="col-md-7 col-md-push-5">
						<div class="booking-cta">
							<h1>Make your Cancelation</h1>
							
						</div>
					</div>
					<div class="col-md-4 col-md-pull-7">
						<div class="booking-form">
					   <form id="booking-form"action="" method="post">
                            {% csrf_token %}
                            <h2 style="color: #000000;">WANT TO CANCEL?{{room_category}}</h2>
                                    <div class="row">
									<div class="col-sm-8">
										<div class="form-group">
										</div>
									</div>
								</div>
								
								<div class="form-btn">
									<button type ="submit" class="btn btn-danger">Cancel</button>
								</div>
							</form>
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</div>

</body>

</html>

hms_prj/hotel/templates/hotel/bookings_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
    <title>Booking List</title>
    <style>
    body {
      position: relative;
      background-image: url('{% static "img/background.jpg" %}');
      background-attachment: fixed;
      background-size: 100%; 
  }
  
    .custom-button {
        margin-left: 20px;
         /* Adjust the value as needed */
    }
</style>
  </head>

<body>
  <div class="container">
    
      

    <h1 style="color: #ffffff; padding-left: 425px; padding-bottom: 10px; padding-top: 25px;"> YOUR BOOKINGS {{user}} </h1>
  </div>
  <a class="btn btn-dark   custom-button"  href="{% url 'hotel:RoomList' %}"> Home</a>
    <DIV class="row" style="padding-left: 25px; padding-top:25px ;">
      
    {% for booking in bookings_list %}
    
    <div class="card " style="width: 18rem; margin: 10px; ">
        <img src="{% static 'img/download.jpeg' %}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{booking.get_room_category}} ROOM</h5>
          <p   class="card-text"><strong>FROM:</strong> {{booking.check_in}}<br><strong>TO: </strong>{{booking.check_out}}<br><strong>BEDS: </strong>{{booking.room.beds}}<br><strong>CAPACITY: </strong>{{booking.room.capacity}}</p>

          <a href="{{booking.get_cancel_booking_url}}" class="btn btn-danger">Cancel Booking</a>
        </div>
      </div>
    {% endfor %}
  </DIV>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

hms_prj/hotel/templates/room_detail_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Room Details</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css'%}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->


</head>
<body>
	<div id="booking" class="section">
		<div class="section-center">
					
	<div class="container">
		<a class="btn btn-danger" href="{% url 'hotel:RoomList' %}"> Home</a>
	</div>
                     
			<div class="container">
				<div class="row">
					<div class="col-md-7 col-md-push-5">
						<div class="booking-cta">
							<h1>Make your reservation</h1>
							<h2 style="color: #ffffff;">FOR {{room_category}} ROOMS </h2>
						</div>
					</div>
					<div class="col-md-4 col-md-pull-7">
						<div class="booking-form">
					   <form id="booking-form"action="" method="post">
                            {% csrf_token %}
                                    <div class="row">
									<div class="col-sm-8">
										<div class="form-group">
											<span for="id_check_in" class="form-label">Check In</span>
											<input class="form-control" id="id_check_in" name="check_in" type="datetime-local" required>
										</div>
									</div>
									<div class="col-sm-8">
										<div class="form-group">
											<span class="form-label" for="id_check_out" for="id_check_out">Check out</span>
											<input class="form-control" id="id_check_out" name="check_out"  type="datetime-local" required>
										</div>
									</div>
								</div>
								
								<div class="form-btn">
									<button class="submit-btn">Check availability</button>
								</div>
							</form>
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</div>

</body>

</html>

hms_prj/hotel/templates/room_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Room List</title>
    <style>
         
        body {
            position: relative;
            background-image: url('{% static "img/background.jpg" %}');
            background-attachment: fixed;
            background-size: 100%; 
        }

    
    </style>
</head>
<body>
    <div class="row ">

        {% for room_category, room_url in room_list %}
            <div class="col-md-2 mb-2 "> <!-- Adjust the column width and margin as needed -->
                <div class="card text-center" style="width: 17rem;  margin:250px 100px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ room_category }} Rooms</h5>
                        <p class="card-text">Welcome To Hotel Raddison</p>
                        <a href="{{ room_url }}" class="btn btn-primary">Book</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>